# Generated by Django 5.0.6 on 2024-05-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.IntegerField(choices=[(0, 'Non_type'), (1, 'Clothes'), (2, 'Food'), (3, 'Game'), (4, 'Data')], default=0),
        ),
    ]
